# Generated by Django 2.2.16 on 2023-02-27 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20230227_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-created',), 'verbose_name': 'Избранный автор', 'verbose_name_plural': 'Избранные авторы'},
        ),
    ]
